### PR TITLE
Improve error checking to Matrix parameters

### PR DESCRIPTION
**Pull request by mutesplash**
De-duplicates code and also allows set_pixels to accept (str,int) as pixel specifications

Allow set_pixels() to defer display updates like set_pixel() does

Also, remove the exception in Device.off() for the Matrix by overriding it

### CODE REVIEW

**Comment by mutesplash** [comment]
Updated!

**Comment by mutesplash** [comment]
I guess I better get flake8 installed if I want this merged.

**Comment by chrisruk** [comment]
Hey, sorry about that, I've just been working on linting the code, you'll need -

```
flake8
flake8-pylint
```

Then you can do: 'PYTHONPATH=. flake8 .' from the main part of the repo.

**Comment by chrisruk** [comment]
This now fails to run the example in docs for me.

With:

```
python3.9 docs/buildhat/matrix.py 
Traceback (most recent call last):
  File "/home/pi/Repositories/python-build-hat/docs/buildhat/matrix.py", line 8, in <module>
    matrix.clear(("red", 10))
  File "/home/pi/Repositories/python-build-hat/buildhat/matrix.py", line 121, in clear
    color = Matrix.normalize_pixel(pixel)  # pylint: disable=too-many-function-args
TypeError: normalize_pixel() takes 1 positional argument but 2 were given
```

Also at the moment I'm not really using the type annotation feature.

I think staticmethod should be used rather than classmethod.

**Comment by mutesplash** [comment]
Ugh, these tuples...

I put the type annotations in to make the linter be quiet.  If you'd rather use the # directives, I'll change it back.  I'll also use the staticmethod.

**Comment by mutesplash** [comment]
Ooookay, turned out those didn't help the linter anyway!  It should work now?

**Pull request merged**
