### PR TITLE
Add the ability to reboot the BuildHAT

### PR DESCRIPTION
**Pull request by mutesplash**
Fairly serious change, but this will allow people to reset fixed counters like the start position on motors and maximum force sensed that can't be reset on the BuildHAT without having to disconnect and reconnect the devices.  From a now-deleted comment in init(), it looks like this feature would be useful.

I moved the port initialization closer to where it's used so it didn't have to be duplicated.

I also isolated the bootloader/firmware state detection to make init() easier to understand and hopefully improved the detection slightly.

I encountered a problem where BuildHAT became unresponsive to serial commands, so I added some code to automatically reboot the HAT on init only.  I was only able to test this code once (and it worked!) as I have no idea how I got the BuildHAT stuck like that.

### CODE REVIEW

**Comment by mutesplash** [comment]
Fixed github's complaints

**Comment by mutesplash** [comment]
Realized I wasn't doing enough testing post-reboot _without_ running a script again and noticed that the ports needed some more serial port commands to be issued after reboot (because some stuff wasn't working...).  Since Device prevents multiple instances, moved the per-port in-use tracking into BuildHAT so it could trigger a reset on each class to set each port to expected values after a reboot.

Fixed the callback queue handling on reboot as well.

Matrix and Light retain their settings across reboot.

**Comment by chrisruk** [comment]
I've had a look at this, but I'm afraid I'd be a little worried with such a substantial change at the moment.  I can ask the firmware devs to see if there might be a way to reset say the max force sensed counter.

**Comment by mutesplash** [comment]
Well that's too bad, because the changes I made to reliably fix the Matrix relies on some of this code. ☹️  Are you just opposed to the idea, the changes I made, or just the changes all at once?  I'm going to make one more push to this branch (after I fix the linter problems) to show you how I fixed the Matrix connection problems.

What about a different PR for just _what_state_are_we_in()?  It's large but isolated.  I have uncommitted changes in that function that keep chatter from improper shutdowns and Matrix re-connecting from causing HatState.OTHER to block startup.

**Comment by mutesplash** [comment]
This patch could be split into pieces.  Would any of these be welcome?

_Discrete, preparatory changes that improve the BuildHAT library in other ways_

1. Improved state detection with the ability to ignore device chatter to start successfully if BuildHAT is in a not-known state.  **Purpose**: Reduce cases where a stuck BuildHAT (ie: too chatty for incdata counter) has to be powered off to get fixed.

2. Switch port in-use tracking in the BuildHAT class to contain weak references to the classes for each port.  Use these references to have classes issue their own known-state shutdown commands instead of having the BuildHAT class know what to do in shutdown().  Add _shutdown() to devices for commands to be sent out over the serial port that leave the devices in a known "unused" state.  **Purpose**: Separation of concerns (and pave the way for BuildHAT to manage the device startup/shutdown)

3. Change loop device detection when firmware already loaded to use the "version" serial command to determine when the list has completed in order to better detect devices connecting during initialization.  Move loop() initialization when in firmware into the function.  Don't unblock init() of BuildHAT until all devices have finished listing out AND any devices coming online have also connected and are enumerated.  **Purpose**: Matrix's on/off ways get captured and halted before the user's app gets unblocked.

_With the above changes, the changes solely to support reboots are_

4. Separation of _startup() out of init() that contains the commands that get sent out via the serial port to initialize a device into a known state and the variables set to reflect this.  

5. Save the firmware file locations to variables for use in loadfirmware()

6. Allow BuildHAT to be reset without affecting any classes instantiated for devices.  Add _startup() calls for instantiated classes while the loop is enumerating them from a list.  **Purpose**: Allow developers to reset the BuildHAT (reset counters, encountered a bug) without having to lose their own state by restarting their own program.

_Once the BuildHAT can be restarted automatically_

7. Reset BuildHAT if its state could not be determined on startup.  **Purpose**: Eliminate stuck BuildHAT states solved by poweroff

**Comment by chrisruk** [comment]
Hi,

I've just had a little look at this pull request re. point 3 with respect to attempting 
to fix the Matrix in software,  however I managed to get the following error unfortunately

```
Traceback (most recent call last):
  File "/home/pi/Repositories/python-build-hat/t.py", line 7, in <module>
    m = Matrix('A')
  File "/home/pi/Repositories/python-build-hat/buildhat/matrix.py", line 24, in __init__
    super().__init__(port)
  File "/home/pi/Repositories/python-build-hat/buildhat/devices.py", line 53, in __init__
    self._startup()
  File "/home/pi/Repositories/python-build-hat/buildhat/matrix.py", line 37, in _startup
    super()._startup()
  File "/home/pi/Repositories/python-build-hat/buildhat/devices.py", line 64, in _startup
    raise DeviceError('There is not a {} connected to port {} (Found {})'.format(type(self).__name__,
buildhat.exc.DeviceError: There is not a Matrix connected to port 0 (Found Disconnected)
```

By instantiating a Light prior to the Matrix.

**Comment by mutesplash** [comment]
I did a clean pull of this patch branch, used the "break the matrix" script from the [other PR](https://github.com/RaspberryPiFoundation/python-build-hat/pull/141#issuecomment-1104576248) and just switched the light to be instantiated first and it worked (and didn't break it). 😕   Maybe the library needs a logging feature 😄

**Comment by mutesplash** [comment]
When I switched back to main, I got the error you posted by running the "break matrix" script.

**Comment by chrisruk** [comment]
The following is what I ran using this pull req., after unplugging the matrix first:

```
#!/usr/bin/python3
from buildhat import Light
from buildhat import Matrix
import time
l = Light('B')
m = Matrix('C')
m.clear(('red', 10))
time.sleep(1)
```

**Comment by mutesplash** [comment]
I got it on the second run.  I'll re-instrument the patch and see if I can catch what's happening on the serial interface.

**Comment by chrisruk** [comment]
Thanks, it's been a little bit since I looked at the code, but iirc, the delay was only being added if the first Device class instantiated was the Matrix, but I could be wrong.

**Pull request closed without merging**
