### PR TITLE
Allow the BuildHAT LEDs to be turned on and off

### PR DESCRIPTION
**Pull request by mutesplash**
Either via the style provided in the serial port interface or as seemingly discrete LEDs.

### CODE REVIEW

**Comment by mutesplash** [comment]
I'm so sorry!  I thought I had this fixed in my editor.  I must have not been careful and tried to fix something on the fly.

**Comment by chrisruk** [comment]
No worries, I'm going to add a github action soon, which will help us spot little things like this :)

**Comment by mutesplash** [comment]
I used github's web interface to manually merge them and didn't count the spaces properly.

**Comment by mutesplash** [comment]
My reasoning for including the orange/green functions is that if somebody wants to just toggle them, they'll end up having to do the BuildHAT-specific logic in their code and that just seemed very domain-specific to the BuildHAT and it could be in the library to save people coming up with the same code and/or introducing their own bugs.

**Pull request merged**
