### PR TITLE
Hack the matrix, by adding a delay to account for the disconnections/connections

### PR DESCRIPTION
**Pull request by chrisruk**

### CODE REVIEW

**Comment by chrisruk** [comment]
Thanks a lot at taking a look at this! Yeah it does seem rather tricky.

**Comment by mutesplash** [comment]
Figured it out.  Prevent BuildHAT from quitting the loop 3 seconds after starting up 😄 Keeps startup from getting slower.  I did it with a bunch of other corner-case solving code (also re-thought my other PRs) so it might take a day or two to sort out into digestible patches.

**Comment by mutesplash** [comment]
Running tests with the passive light in tandem with the matrix I noticed that the plimit set to anything but 1 seems to affect if the Matrix reboots itself during connection.  If you have access to the firmware source, this might be a thing to look at.  It doesn't seem like a very good thing to set as a global in general, because the Motor and Light class just sets it like it's per-port and several other classes seem like they need it set to full power (1).  If you drop it to zero, the Matrix will turn off and won't come back unless you physically remove it.  Also, if you reconnect it with plimit set below 1, it will go into a disconnect/reconnect loop.

**Comment by mutesplash** [comment]
Break the Matrix:

```
import time
import buildhat
from buildhat import Matrix, Light

matrix_c = Matrix('C')
light_d = Light('D')
matrix_c.clear((4,10))
light_d.brightness(0)
print("DISCONNECT AND RECONNECT MATRIX NOW!")
time.sleep(10)


light_d.brightness(100)
matrix_c.clear((4,10))

time.sleep(10)
```

Fix the Matrix:

```
import serial
import time

ser = serial.Serial("/dev/serial0", 115200, timeout=1)

while True:
	try:
		line = ser.readline().decode('utf-8', 'ignore')
		if len(line) > 0:
			print(line)
			if line == "P2: connected to active ID 40\r\n":
				ser.write(b"port 2 ; on ; plimit 1\r")
				break
	except serial.SerialException as e:
		raise e

```

**Comment by chrisruk** [comment]
Cleaned up commit history and moved to #178

**Pull request closed without merging**
