### PR TITLE
Fix the ultrasonic distance sensor LEDs

### PR DESCRIPTION
**Pull request by mutesplash**
Also indicate which LED each value illuminates

Reverse was being called in the class initialization which wrote it out to the serial port, however, it didn't seem to "stick" unless the port was turned on first and prevented the LEDs from functioning.

### CODE REVIEW

**Comment by mutesplash** [comment]
As soon as you use DistanceSensor.on(), the "set -1" serial command that is sent to initialize the port is cleared out and never reset.  If you put

```
d.on()
d.off()
```

anywhere before "d.eyes()" it won't work anymore.  If you enclose the eyes() call within an on() off() series of calls, it won't work either.  I've had it work _once_ while testing permutations of this, but it seems like a race condition.  Subsequent runs of the program don't work without the patch.

**Comment by mutesplash** [comment]
Alright, if you put d.get() above an on()/off() toggle, it will work.  Also, get() is part of the device base class.  Why should this be called to initialize it?

**Comment by chrisruk** [comment]
Sorry I think I misunderstood what you where doing before, normally you shouldn't have to use the .on(),.off(),.reverse() functions directly.

I've just overrode .on() now for the distance sensor so that it sends set -1.  It shouldn't call
```
super().on()
```
though too, as that would send 'set 1' also.

The sensor calls 'set -1' too in the init function, so that .get() etc. calls function correctly.

**Comment by mutesplash** [comment]
I tested it out and it seemed to work great.  Can we still add some documentation to the order of the LED parameters?

**Pull request merged**
